---
- name: Implementing loops
  hosts: all
  tasks: 
   - name: Install s/w applications
     apt: 
       name: "{{item}}"
       state: present
       update_cache: yes
     with_items: 
       - maven
       - git
       - openjdk-17-jdk
...
