---
- name: Configuring apache2
  hosts: all
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: check url response  
    - name: Edit the content of the file
      copy:
        content: "Manoj=Kumar"
        dest: /var/www/html/index.html
      notify: Restart apache
  handlers: 
    - name: Restart apache
      service: 
        name: apache2
        state: restarted
    - name: check url response
      uri: 
        url: "{{item}}"
        status_code: 200
      with_items: 
        - http://172.31.47.200
        - http://172.31.44.160
        - http://172.31.42.210
        - http://172.31.43.120 
...          

