---
- name: Error handling or Exception handling
  hosts: all
  tasks: 
    - block: 
        - name: Install git on ubuntu
          apt: 
            name: git
            state: present
            update_cache: yes
      rescue: 
        - name: Install git on redhat
          yum: 
            name: git
            state: present
            update_cache: yes
      always: 
        - name: Print sucess message
          debug: 
            msg: "Git Installation Sucessfull"
...              
