---
- name: Install tomcat10 and restart
  hosts: all
  tasks: 
    - name: Install tomcat10
      apt: 
        name: tomcat10
        state: absent
        update_cache: yes
    - name: Restart tomcat10
      service: 
        name: tomcat10
        state: stopped

...      
