---
- name: Create a user and create a file/dir in user home dir
  hosts: all
  tasks: 
    - name: Create a user
      user: 
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: Create a file/dir in user home dir
      file: 
        name: "{{d}}"
        state: "{{e}}"

...
