---
- name: Create multiple users and copy files to users home dir
  hosts: all
  tasks: 
    - name: Create user
      user: 
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: Rajesh,b: admin,c: /home/Rajesh}
        - {a: Ramesh,b: admin,c: /tmp/Ramesh}
    - name: copy files to users home dir
      copy: 
        src: "{{item.a}}"
        dest: "{{item.b}}"
        owner: "{{item.c}}"
        group: "{{item.d}}"
      with_items:
        - {a: /etc/passwd,b: /home/Rajesh,c: Rajesh,d: Ramesh}
        - {a: /etc/group,b: /tmp/Ramesh,c: Ramesh,d: Rajesh}
...           



