---
- name: Implementing host scope variable
  hosts: 172.31.43.120
  tasks: 
    - name: User creation
      user: 
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        uid: "{{d}}"
        comment: "{{e}}"
        shell: "{{f}}"
...
