---
- name: Install tree on all servers
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install tree on Ubuntu
      apt:
        name: tree
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install tree on RedHat
      yum:
        name: tree
        state: present
      when: ansible_distribution == "RedHat"

